"""Findings report renderer (Markdown) per the AGENT_BRIEF template.

Platform templates (HackerOne/Bugcrowd/Intigriti/generic) live in
``templates/reports/`` and only add a submission-format preamble; the
findings body is platform-independent and sanitized to proof-only
evidence.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from core.sanitizer import sanitize_evidence, sanitize_finding
from lib.logger import get_logger
from lib.paths import TEMPLATES_DIR
from lib.utils import utc_timestamp

logger = get_logger("reporter")

_PLATFORM_FILES = {
    "hackerone": "hackerone.md",
    "bugcrowd": "bugcrowd.md",
    "intigriti": "intigriti.md",
}


def _platform_preamble(platform: str) -> str:
    """Load the platform-specific report preamble (falls back to generic)."""
    fname = _PLATFORM_FILES.get((platform or "").lower(), "generic.md")
    path = TEMPLATES_DIR / "reports" / fname
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def render_finding_section(idx: int, f: dict[str, Any]) -> str:
    """Render one finding block."""
    tools = ", ".join(f.get("tools_found", []) or []) or "-"
    payload = str(f.get("payload", "") or "-")
    response = str(f.get("response_snippet", "") or "-")
    steps = f.get("steps_to_reproduce") or []
    steps_text = "\n".join(f"   {i}. {s}" for i, s in enumerate(steps, start=1)) or "   (see endpoint + payload)"
    return f"""### Finding {idx}: {f.get('vuln_type', 'unknown')} at {f.get('endpoint', '?')}

**Type:** {f.get('vuln_type', '?')}
**Severity:** {f.get('severity', '?')}
**Confidence:** {f.get('confidence', '?')}%
**Tools Found:** {tools}
**State:** {f.get('fp_state', 'VALID')} — {f.get('validity_reason', '')}

**Endpoint:** `{f.get('endpoint', '?')}`
**Payload:** `{payload}`

**Response:**
```
{response}
```

**Impact:** {f.get('impact', '(describe impact)')}
**Steps to Reproduce:**
{steps_text}
---
"""


def render_chains_section(chains: list[dict[str, Any]]) -> str:
    """Render the vulnerability-chains section."""
    if not chains:
        return ""
    blocks = []
    for i, c in enumerate(chains, start=1):
        steps = "\n".join(f"   {s}" for s in c.get("steps", []))
        blocks.append(
            f"### Chain {i}: {c.get('chain_type', '?')}\n\n"
            f"{steps}\n\n"
            f"**Overall Impact:** {c.get('impact', '?')}\n"
            f"**Combined Severity:** {c.get('combined_severity', '?')}\n\n---\n"
        )
    return "## Vulnerability Chains\n\n" + "\n".join(blocks)


def render_draft(
    platform: str,
    target: str,
    finding: dict[str, Any],
    metrics: dict[str, Any] | None = None,
) -> str:
    """Render a single-finding submission draft in a platform's format (roadmap E5)."""
    f = sanitize_finding(finding)
    preamble = _platform_preamble(platform)
    body = render_finding_section(1, f)
    metrics_line = ""
    if metrics:
        metrics_line = (
            f"\n_Scan metrics: {metrics.get('findings_total', 0)} findings, "
            f"{metrics.get('findings_valid', 0)} valid._\n"
        )
    return f"{preamble}\n# Submission Draft — {target}\n{metrics_line}\n## Finding\n\n{body}"


def render_report(
    target: str,
    platform: str,
    program_type: str,
    scope_kind: str,
    metrics: dict[str, Any],
    findings: list[dict[str, Any]],
    chains: list[dict[str, Any]] | None = None,
    scan_date: str | None = None,
) -> str:
    """Render the full findings report (Markdown)."""
    chains = chains or []
    by_sev = metrics.get("by_severity", {})
    sev_line = ", ".join(f"{k}: {v}" for k, v in sorted(by_sev.items())) or "none"

    header = f"""{_platform_preamble(platform)}
# NEXUS Findings Report

**Target:** {target}
**Platform:** {platform}
**Type:** {program_type}
**Scan Date:** {scan_date or utc_timestamp()}

## Metrics

- URLs Discovered: {metrics.get('urls_discovered', 0)}
- Endpoints Tested: {metrics.get('endpoints_tested', 0)}
- Findings Total: {metrics.get('findings_total', 0)}
- Findings Valid: {metrics.get('findings_valid', 0)}
- Findings OOS: {metrics.get('findings_oos', 0)}
- By Severity: {sev_line}
- Chains Detected: {metrics.get('chains_detected', 0)}

## Findings

"""
    body = "\n".join(
        render_finding_section(i, sanitize_finding(f)) for i, f in enumerate(findings, start=1)
    )
    chains_section = render_chains_section(chains)
    summary = f"""
## Summary

- Real Findings: {metrics.get('findings_valid', 0)}
- Potential (needs review): {metrics.get('findings_potential', 0)}
- False Positives (filtered): {metrics.get('false_positives', 0)}
- Out of Scope (blocked from submission): {metrics.get('findings_oos', 0)}

*Generated by NEXUS Framework — detection + PoC only.*
"""
    return header + body + "\n" + chains_section + summary


def write_report(
    results_dir: Path,
    domain: str,
    platform: str,
    program_type: str,
    scope_kind: str,
    metrics: dict[str, Any],
    findings: list[dict[str, Any]],
    chains: list[dict[str, Any]] | None = None,
    scan_date: str | None = None,
) -> Path:
    """Render and write the findings report into the scan's reports/ dir."""
    from lib.utils import findings_report_name

    reports_dir = results_dir / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    name = findings_report_name(domain, platform, program_type, scope_kind, date=scan_date)
    path = reports_dir / name
    text = render_report(
        target=domain,
        platform=platform,
        program_type=program_type,
        scope_kind=scope_kind,
        metrics=metrics,
        findings=findings,
        chains=chains,
        scan_date=scan_date,
    )
    path.write_text(text, encoding="utf-8")
    logger.info("report written: %s", path)
    return path
