"""CVE PoC generator — DETECTION-ONLY artifacts.

For a matched CVE, generates four artifacts under
``scripts/cve_pocs/{cve-id}/``:

- ``{cve-id}.py``   — requests-based marker check (VULNERABLE/NOT_VULNERABLE)
- ``{cve-id}.js``   — fetch-based marker check
- ``{cve-id}.sh``   — curl + grep marker check (read-only)
- ``{cve-id}.yaml`` — nuclei template with version/status/body matchers

Every artifact embeds the NEXUS security-boundary header
(detection + PoC only, no extraction) and uses only payload-guard
approved detection markers. The generated ``.sh`` uses the
``.nexus-poc.sh`` suffix convention so the tool-command guard can
whitelist it for execution.
"""
from __future__ import annotations

from pathlib import Path
from textwrap import dedent
from typing import Any

from lib.paths import REPO_ROOT

POC_HEADER = (
    "# NEXUS generated detection PoC — {cve_id}\n"
    "# SECURITY BOUNDARY: detection + proof-of-concept only.\n"
    "# No data extraction, no destructive requests, no shells.\n"
    "# Generated by NEXUS Framework for authorized bug bounty use.\n"
)

_CVE_DIR_RE = Any  # documentation only


def _cve_dir(cve_id: str, base: Path | None = None) -> Path:
    safe = (cve_id or "").strip().lower().replace("/", "-").replace("\\", "-")
    root = (base or REPO_ROOT / "scripts" / "cve_pocs") / safe
    return root


def _marker(cve: dict[str, Any]) -> str:
    """Pick a benign detection marker from the CVE record."""
    m = str(cve.get("detection_marker", "") or "")
    if m:
        return m
    desc = str(cve.get("description", ""))
    # Default marker: a version banner pattern supplied by the operator.
    return str(cve.get("version_marker", "") or "CHANGE_ME_VERSION_MARKER")


def _target_url(cve: dict[str, Any]) -> str:
    return str(cve.get("target_url", "") or "https://TARGET_HOST/")


def generate_python_poc(cve: dict[str, Any]) -> str:
    """Render the Python detection PoC source."""
    cve_id = cve.get("cve_id", "CVE-XXXX-YYYY")
    marker = _marker(cve)
    url = _target_url(cve)
    return dedent(POC_HEADER).format(cve_id=cve_id) + dedent(f'''\
        """Detection-only PoC for {cve_id}."""
        import sys

        import requests


        def check(target_url: str = "{url}", timeout: int = 10) -> str:
            """GET the target and compare the fingerprint marker.

            Prints VULNERABLE or NOT_VULNERABLE; extracts nothing.
            """
            try:
                resp = requests.get(target_url, timeout=timeout)
            except requests.RequestException as exc:
                print(f"ERROR: {{exc}}")
                return "ERROR"
            marker = {marker!r}
            if marker and marker.lower() in resp.text.lower():
                print("VULNERABLE: marker present")
                return "VULNERABLE"
            print("NOT_VULNERABLE: marker absent")
            return "NOT_VULNERABLE"


        if __name__ == "__main__":
            target = sys.argv[1] if len(sys.argv) > 1 else "{url}"
            check(target)
        ''')


def generate_js_poc(cve: dict[str, Any]) -> str:
    """Render the JavaScript (fetch-based) detection PoC."""
    cve_id = cve.get("cve_id", "CVE-XXXX-YYYY")
    marker = _marker(cve)
    url = _target_url(cve)
    return dedent(POC_HEADER).format(cve_id=cve_id) + dedent(f'''\
        // Detection-only PoC for {cve_id}
        const TARGET = "{url}";
        const MARKER = {marker!r};

        async function check() {{
            try {{
                const resp = await fetch(TARGET);
                const text = await resp.text();
                if (MARKER && text.toLowerCase().includes(MARKER.toLowerCase())) {{
                    console.log("VULNERABLE: marker present");
                    return "VULNERABLE";
                }}
                console.log("NOT_VULNERABLE: marker absent");
                return "NOT_VULNERABLE";
            }} catch (err) {{
                console.log("ERROR: " + err.message);
                return "ERROR";
            }}
        }}

        check();
        ''')


def generate_sh_poc(cve: dict[str, Any]) -> str:
    """Render the Bash (curl + grep, read-only) detection PoC."""
    cve_id = cve.get("cve_id", "CVE-XXXX-YYYY")
    marker = _marker(cve)
    url = _target_url(cve)
    return dedent(POC_HEADER).format(cve_id=cve_id) + dedent(f'''\
        # Detection-only PoC for {cve_id} (read-only curl + grep)
        TARGET="${{1:-{url}}}"
        MARKER={marker!r}

        BODY="$(curl -s --max-time 10 "$TARGET")"
        if echo "$BODY" | grep -qi "$MARKER"; then
            echo "VULNERABLE: marker present"
            exit 0
        fi
        echo "NOT_VULNERABLE: marker absent"
        exit 1
        ''')


def generate_nuclei_template(cve: dict[str, Any]) -> str:
    """Render a nuclei YAML template with benign matchers."""
    cve_id = str(cve.get("cve_id", "") or cve.get("cve-id", "CVE-XXXX-YYYY"))
    marker = _marker(cve)
    url = _target_url(cve)
    severity = str(cve.get("severity", "high")).lower()
    desc = str(cve.get("description", ""))[:300].replace('"', "'")
    cpe = str(cve.get("cpe", "") or "").strip()
    cpe_matcher = ""
    if cpe:
        cpe_matcher = f'      - type: cpe\n        cpe:\n          - "{cpe}"\n'
    return dedent(f'''\
        id: {cve_id}-detection
        info:
          name: {cve_id} version-marker detection
          author: NEXUS Framework
          severity: {severity}
          description: |
            {desc}
            Detection-only template: matches a version/marker banner and
            performs no extraction or destructive requests.
        requests:
          - method: GET
            path:
              - "{url}"
            matchers:
              - type: word
                part: body
                words:
                  - "{marker}"
              - type: status
                status:
                  - 200
        {cpe_matcher}''')


_NUCLEI_TPL_RE = None  # placeholder for future template validation


def generate_all(cve: dict[str, Any], base_dir: Path | None = None) -> dict[str, Path]:
    """Generate all four artifacts; returns their paths."""
    cve_id = str(cve.get("cve_id", "") or cve.get("cve-id", "") or "CVE-XXXX-YYYY")
    root = _cve_dir(cve_id, base=base_dir)
    root.mkdir(parents=True, exist_ok=True)

    artifacts = {
        "python": root / f"{cve_id}.py",
        "js": root / f"{cve_id}.js",
        "sh": root / f"{cve_id}.sh",
        "nuclei": root / f"{cve_id}.yaml",
    }

    artifacts["python"].write_text(generate_python_poc({**cve, "cve_id": cve_id}), encoding="utf-8")
    artifacts["js"].write_text(generate_js_poc({**cve, "cve_id": cve_id}), encoding="utf-8")
    # .sh uses the whitelisted suffix for the tool-command guard.
    sh_path = root / f"{cve_id}.nexus-poc.sh"
    sh_path.write_text(generate_sh_poc({**cve, "cve_id": cve_id}), encoding="utf-8")
    artifacts["sh"] = sh_path
    artifacts["nuclei"].write_text(
        generate_nuclei_template({**cve, "cve_id": cve_id}), encoding="utf-8"
    )
    return artifacts


def register_nuclei_template(yaml_path: Path, templates_dir: Path | None = None) -> Path:
    """Copy a generated nuclei template into templates/nuclei-custom/."""
    import shutil

    target_dir = templates_dir or (REPO_ROOT / "templates" / "nuclei-custom")
    target_dir.mkdir(parents=True, exist_ok=True)
    dest = target_dir / yaml_path.name
    shutil.copyfile(yaml_path, dest)
    return dest
